#!/usr/bin/python

COMMAND="unzip"

import sys
import json
import tempfile
import subprocess

if __name__=='__main__':
    try:
        tempdir=tempfile.mkdtemp()
        result=subprocess.check_output([COMMAND, '-d', tempdir, sys.argv[1]])
        print json.JSONEncoder().encode({'content': result, \
            'is_container': True, \
            'extracted': tempdir})
        sys.exit(0)
    except Exception, e:
        print e
        sys.exit(2)
