#!/usr/bin/python

import sys
import json

if __name__=='__main__':
    try:
        f = open(sys.argv[1], 'r')
        print json.JSONEncoder().encode({'plaintext': f.read()})
        f.close()
        sys.exit(0)
    except Exception, e:
        print e
        sys.exit(2)
